Refactor/21 refactoring download
Kandimus/ctagssh pull request #31
Opened 2022-06-03 12:37 UTC by MicSm

2022-06-06 16:36 UTC, Kandimus requested changes

2022-06-06 16:36 UTC, Kandimus commented on src/extension.js
>  var sshvf = require('./TextDocumentProvider.js');
Do clear unused modules on line 1..10

2022-06-07 06:17 UTC, MicSm commented on src/extension.js
>  var sshvf = require('./TextDocumentProvider.js');
fixed

2022-06-07 06:24 UTC, Kandimus approved these changes

2022-06-07 06:24 UTC, merged